**0000**

In [2]:
import tensorflow as tf;
print(tf.__version__)

2.15.0


In [3]:
scaler = tf.constant(7);
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scaler.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,2], [3,5]]);
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 5]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[1,2], [2,4], [1,1]],dtype=tf.float16);
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 4.],
       [1., 1.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [12]:
change_tensor = tf.Variable([10,7]);
unchangeable_tensor = tf.constant([10,7]);

In [13]:
change_tensor[0].assign(7);
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# unchangeable_tensor[0] = 7;

In [15]:
random_tensor = tf.random.Generator.from_seed(42.);
random_1 = random_tensor.normal(shape=(3,2));
random_1

random_tensor = tf.random.Generator.from_seed(42.);
random_2 = random_tensor.normal(shape=(3,2));
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.30101568,  0.51859164],
       [-0.15693977, -1.1760874 ],
       [ 0.2227503 , -0.7936496 ]], dtype=float32)>

In [16]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.30101568,  0.51859164],
        [-0.15693977, -1.1760874 ],
        [ 0.2227503 , -0.7936496 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.30101568,  0.51859164],
        [-0.15693977, -1.1760874 ],
        [ 0.2227503 , -0.7936496 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
not_shuffled = tf.constant([[1,2], [2,3], [3,4]]);
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [18]:
shuffled_tensor = tf.random.shuffle(not_shuffled);
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [2, 3],
       [1, 2]], dtype=int32)>

In [19]:
tf.random.set_seed(42);
shuffled_tensor_2 = tf.random.shuffle(not_shuffled, seed=42);
shuffled_tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [20]:
tf_ones = tf.ones([10,7]);
tf_ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf_zeros = tf.zeros([10,7]);
tf_zeros

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
import numpy as np

In [23]:
np_array = np.arange(1,25, dtype=np.int32);
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(np_array)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
A = tf.Variable(np_array)
A

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [26]:
A = tf.constant(np_array, shape= (3,4,2))
A, A.ndim


(<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>,
 3)

In [27]:
rank_4_tensor = tf.zeros(shape=(3,3,4,5))
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor),tf.size(rank_4_tensor).numpy()

(TensorShape([3, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=180>,
 180)

In [28]:
first_2 = rank_4_tensor[:,:,: ,-1]
first_2

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [29]:
tensor_2 = tf.constant([[10,7,1], [3,4,1]]);
tensor_2.shape, tensor_2.ndim, tf.size(tensor_2)


(TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [30]:
tensor_2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [31]:
# tensor_2
tensor_3 = tensor_2[tf.newaxis,... ]
tensor_3

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[10,  7,  1],
        [ 3,  4,  1]]], dtype=int32)>

In [32]:
tensor_4 = tf.expand_dims(tensor_2, axis=-1
                          )
tensor_4

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 7],
        [ 1]],

       [[ 3],
        [ 4],
        [ 1]]], dtype=int32)>

In [33]:
tensor_x = tf.constant([[10,7], [2,3],[2,3]])

tensor_x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 2,  3]], dtype=int32)>

In [34]:
tensor_y = tf.constant([[1,2], [2,3],[3,4]])
# tensor_x - tensor_y
# tensor_x @ tensor_y


tensor_y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [35]:
tensor_y = tf.reshape(tensor_y, shape=(2,3))
tensor_x,  tensor_y,
tf.matmul(tensor_x, tensor_y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[31, 41, 48],
       [11, 13, 16],
       [11, 13, 16]], dtype=int32)>

In [36]:
tensor_d = tf.constant([1,2,3], dtype=tf.float32)
tensor_d

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [37]:
tensor_d = tf.cast(tensor_d, dtype=tf.float16)
tensor_d

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

In [38]:
d = tf.constant([-110,7])
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([110,   7], dtype=int32)>

In [39]:
tf.argmax(d).numpy()


1

In [40]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[1,1,1,1,1,50]);
F

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [41]:
F_squeed = tf.squeeze(F)
F_squeed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [42]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [43]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [44]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [45]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [2]:
tf.config.list_physical_devices()

NameError: name 'tf' is not defined

In [3]:
!nvidia-smi

Sat Jul 27 08:13:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--